name: Deploy AIMCS Frontend to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          # Clean up to fix Rollup issue
          rm -rf node_modules package-lock.json
          npm install

      - name: Debug secrets before build
        run: |
          echo "Checking if secrets are available:"
          echo "ENDPOINT exists: ${{ secrets.VITE_AZURE_OPENAI_ENDPOINT != '' }}"
          echo "API_KEY exists: ${{ secrets.VITE_AZURE_OPENAI_API_KEY != '' }}"
          echo "DEPLOYMENT exists: ${{ secrets.VITE_AZURE_OPENAI_DEPLOYMENT != '' }}"
          echo "BACKEND_URL exists: ${{ secrets.VITE_BACKEND_API_URL != '' }}"
          echo "ENDPOINT value: ${{ secrets.VITE_AZURE_OPENAI_ENDPOINT }}"
          echo "DEPLOYMENT value: ${{ secrets.VITE_AZURE_OPENAI_DEPLOYMENT }}"
          echo "BACKEND_URL value: ${{ secrets.VITE_BACKEND_API_URL }}"
          echo "API_KEY exists: ${{ secrets.VITE_AZURE_OPENAI_API_KEY != '' }}"
          
          # Set environment variables for the build step
          echo "VITE_AZURE_OPENAI_ENDPOINT=${{ secrets.VITE_AZURE_OPENAI_ENDPOINT }}" >> $GITHUB_ENV
          echo "VITE_AZURE_OPENAI_API_KEY=${{ secrets.VITE_AZURE_OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "VITE_AZURE_OPENAI_DEPLOYMENT=${{ secrets.VITE_AZURE_OPENAI_DEPLOYMENT }}" >> $GITHUB_ENV
          echo "VITE_BACKEND_API_URL=${{ secrets.VITE_BACKEND_API_URL }}" >> $GITHUB_ENV
          
          echo "Environment variables set for build step:"
          echo "VITE_AZURE_OPENAI_ENDPOINT: ${{ secrets.VITE_AZURE_OPENAI_ENDPOINT }}"
          echo "VITE_AZURE_OPENAI_DEPLOYMENT: ${{ secrets.VITE_AZURE_OPENAI_DEPLOYMENT }}"
          echo "VITE_BACKEND_API_URL: ${{ secrets.VITE_BACKEND_API_URL }}"

      - name: Build Vite app
        env:
          VITE_AZURE_OPENAI_ENDPOINT: ${{ secrets.VITE_AZURE_OPENAI_ENDPOINT }}
          VITE_AZURE_OPENAI_API_KEY: ${{ secrets.VITE_AZURE_OPENAI_API_KEY }}
          VITE_AZURE_OPENAI_DEPLOYMENT: ${{ secrets.VITE_AZURE_OPENAI_DEPLOYMENT }}
          VITE_BACKEND_API_URL: ${{ secrets.VITE_BACKEND_API_URL }}
        run: npm run build

      - name: Debug built files
        run: |
          echo "Checking if environment variables were injected:"
          if [ -d "dist/assets" ]; then
            echo "Built JS files found:"
            ls -la dist/assets/
            echo "Checking for environment variables in built files:"
            for jsfile in dist/assets/*.js; do
              if [ -f "$jsfile" ]; then
                echo "Checking file: $jsfile"
                grep -o "VITE_AZURE_OPENAI_ENDPOINT" "$jsfile" || echo "ENDPOINT not found in $jsfile"
                grep -o "VITE_AZURE_OPENAI_DEPLOYMENT" "$jsfile" || echo "DEPLOYMENT not found in $jsfile"
                grep -o "VITE_BACKEND_API_URL" "$jsfile" || echo "BACKEND_URL not found in $jsfile"
                echo "---"
              fi
            done
          else
            echo "No dist/assets directory found"
            ls -la dist/
          fi

      - name: Upload artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: aimcs-frontend-eastus2
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure Web App environment variables
        run: |
          az webapp config appsettings set \
            --name aimcs-frontend-eastus2 \
            --resource-group aimcs-rg-eastus2 \
            --settings \
            VITE_AZURE_OPENAI_ENDPOINT="${{ secrets.VITE_AZURE_OPENAI_ENDPOINT }}" \
            VITE_AZURE_OPENAI_API_KEY="${{ secrets.VITE_AZURE_OPENAI_API_KEY }}" \
            VITE_AZURE_OPENAI_DEPLOYMENT="${{ secrets.VITE_AZURE_OPENAI_DEPLOYMENT }}" \
            VITE_BACKEND_API_URL="${{ secrets.VITE_BACKEND_API_URL }}"

      - name: Debug secrets
        run: |
          echo "ENDPOINT=${{ secrets.VITE_AZURE_OPENAI_ENDPOINT }}"
          echo "DEPLOYMENT=${{ secrets.VITE_AZURE_OPENAI_DEPLOYMENT }}"
          echo "BACKEND_URL=${{ secrets.VITE_BACKEND_API_URL }}"
          echo "API_KEY length: ${#VITE_AZURE_OPENAI_API_KEY}"
        env:
          VITE_AZURE_OPENAI_API_KEY: ${{ secrets.VITE_AZURE_OPENAI_API_KEY }} 